version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fastfood-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fastfood-network

volumes:
  postgres-data:

networks:
  fastfood-network:
    driver: bridge