apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secrets.yaml

images:
  - name: felixgilioli/fastfood-service
    newTag: latest

replacements:
  - source:
      kind: Secret
      name: fastfood-service-secret
      fieldPath: stringData.MERCADO_PAGO_ACCESS_TOKEN
    targets:
      - select:
          kind: Secret
          name: fastfood-service-secret
        fieldPaths:
          - stringData.MERCADO_PAGO_ACCESS_TOKEN