apiVersion: v1
kind: Secret
metadata:
  name: fastfood-service-secret
  namespace: tcc
stringData:
  MERCADO_PAGO_ACCESS_TOKEN: "${MERCADO_PAGO_ACCESS_TOKEN}"
  DB_URL: "postgres.c8dwiaao0aet.us-east-1.rds.amazonaws.com"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"