version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: felixgilioli-fastfood-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - felixgilioli-fastfood-network

  app:
    image: felixgilioli/fastfood-service
    container_name: felixgilioli-fastfood-service
    environment:
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8080:8080"
    networks:
      - felixgilioli-fastfood-network

volumes:
  postgres-data:

networks:
  felixgilioli-fastfood-network:
    driver: bridge