name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Build da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            felixgilioli/fastfood-service:latest
            felixgilioli/fastfood-service:v${{ github.run_number }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload da imagem como artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image.tar

  push-dockerhub:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download da imagem
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load da imagem Docker
        run: docker load --input /tmp/image.tar

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da Imagem Docker
        run: |
          docker push felixgilioli/fastfood-service:latest
          docker push felixgilioli/fastfood-service:v${{ github.run_number }}